# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TypicalAnimationContents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TypicalAnimationContents
  pod 'FontAwesome.swift'
  pod 'TransitionableTab', '~> 0.2.0'
end

# TransitionableTabのライブラリバージョンをSwift4.2に固定する
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['TransitionableTab'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end

