# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MediaStyleAnimationContents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MediaStyleAnimationContents
 
  # その他の処理で利用するライブラリ
  pod 'SwiftyJSON'
  pod 'Alamofire' 
  pod 'PromiseKit'
  pod 'AlamofireImage'

  # UI実装で利用するライブラリ
  pod 'FontAwesome.swift'
  pod 'Floaty'
  pod 'FSPagerView'
  pod 'SVProgressHUD'
  pod 'BTNavigationDropdownMenu'
  pod 'PullUpController'
  pod 'ActiveLabel'
  pod 'Toast-Swift', '~> 4.0.0'
end
