# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PurchasePresentContents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PurchasePresentContents

  # 1. API通信や設計等で利用するライブラリ
  pod 'Alamofire'
  pod 'PromiseKit'
  pod 'PINRemoteImage'

  # 2. UI表現の構築に関連するライブラリ
  pod 'DeckTransition'
  pod 'AnimatedCollectionViewLayout'
  pod 'YNDropDownMenu'
  pod 'DeckTransition'
  pod 'PinterestSegment'
  pod 'View2ViewTransition'
  pod 'FloatingPanel'
end
