# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PurchasePresentContents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PurchasePresentContents

  # その他の処理で利用するライブラリ
  pod 'Alamofire'
  pod 'PINRemoteImage'

  # UIレシピブックVol.1でも紹介したライブラリ
  pod 'FontAwesome.swift'

  # UI実装で今回新しく紹介するライブラリ
  pod 'StepIndicator'
  pod 'DeckTransition'
  pod 'AnimatedCollectionViewLayout'
  pod 'DeckTransition'
  pod 'PinterestSegment'
  pod 'ARNTransitionAnimator'
  pod 'FloatingPanel'
  pod 'SkeletonView'
  pod 'Cosmos'
end
